# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
#source 'https://github.com/CocoaPods/Specs.git'
platform :ios,'8.0'
#use_frameworks!
#inhibit_all_warnings!
target 'Test_useReactCocoa' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks

  pod 'ReactiveObjC'

end
